### ISSUE TITLE
Suggestion: show currency name when it's not USD

### ISSUE THREAD

**Issue by alokmenghrajani** [openaccounting/oa-web#62]
If a transaction involves a non-USD account, the frontend currently uses `$` in various views (dashboard, balance sheet, income statement).

I suggest to replace `$` with the currency's code (e.g. EUR, CHF, etc.) when the currency is not USD.

At a later point, the backend and frontend code could be updated to allow the user to provide various metadata for a given currency (preferred thousand and decimal separator, optional currency code, etc.)

**Comment by pnagurny** [comment]
Thanks for the contribution Alok! This is been something I've been meaning to do for awhile but never got around to it. How do you feel about using currency symbols for USD, EUR and GBP ($, €, £) and then defaulting to your behavior otherwise?

**Comment by alokmenghrajani** [comment]
I can update my PR to show the symbol for common ones. I'll pick the one-character symbols from https://en.wikipedia.org/wiki/Currency_symbol.

**Comment by pnagurny** [comment]
Thanks, that would be perfect.

**Comment by alokmenghrajani** [comment]
Expect an updated PR by the end of next week.

**Comment by pnagurny** [comment]
Great idea using Intl.NumberFormat. I'll go ahead and merge your PR.
